server:
  port: 8083
spring:
  application:
    name: register-server
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8082/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: peer2
management:
  endpoint:
    env:
      enabled: true

