server:
  port: 9000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jessiexzx/springcloud-learn.git
          username:
          password:
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@172.25.211.5:8080/eureka
  instance:
    prefer-ip-address: true