server:
  port: 8082
spring:
  application:
    name: register-server
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@peer1:8083/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: peer1
management:
  endpoint:
    env:
      enabled: true