server:
  port: 8080
spring:
  application:
    name: register-server
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: 172.25.211.5
management:
  endpoint:
    env:
      enabled: true